name: Build and test Octave container image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Octave build image version to build and test'
        required: true
        type: choice
        options:
          - 11.3.0
        default: '11.3.0'

env:
  OCTAVE_LATEST: 11.3.0

jobs:
  octave:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      
      - name: Determine build image version
        run: |
          VER=${{ matrix.version }}
          BUILD_VER=${VER%%.*}
          GNU_MIRROR=https://ftpmirror.gnu.org/octave
          echo "OCTAVE_VERSION_MAJOR=${BUILD_VER}" >> $GITHUB_ENV
          echo "GNU_MIRROR=${GNU_MIRROR}" >> $GITHUB_ENV
      
      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: Dockerfile
          build-args: |
            OCTAVE_VERSION=${{ matrix.version }}
            OCTAVE_VERSION_MAJOR=${{ env.OCTAVE_VERSION_MAJOR }}
            GNU_MIRROR=${{ env.GNU_MIRROR }}
          push: false
          tags: |
            reprostat/octave:${{ matrix.version }}

      - name: Check Octave version
        run: |
          VERSION_REQ=${{ matrix.version }}
          VERSION_CHECK=$(docker run -ti reprostat/octave:${{ matrix.version }} octave --eval "ver Octave" | grep -oP '(?<=GNU Octave Version: )[0-9\.]*')
          if [[ "xx${VERSION_REQ}xx" != "xx${VERSION_CHECK}xx" ]]; then exit 1; fi
      - name: Check AWS CLI
        run: |
          docker run -ti reprostat/octave:${{ matrix.version }} aws --version
      - name: Check conda
        run: |
          docker run -ti reprostat/octave:${{ matrix.version }} /bin/bash -c ". /opt/software/config/conda_bash.sh;conda --version"
